{ config, pkgs, ... }:

{
  imports =
  [
    ./hardware-configuration.nix # Auto-generated by nixos
    ./nixos-in-place.nix

    ./system/grub.nix
    ./system/environment.nix
    ./system/network.nix
    ./system/user.nix
    ./system/systemd.nix

    ./program/essentials.nix
    ./program/admin.nix

    ./user/irc.nix
    ./user/git.nix
    ./user/jeaye.nix

    ./service/ssh.nix
    ./service/acme.nix
    ./service/httpd.nix
    ./service/postfix.nix
    ./service/dovecot.nix
    ./service/opendkim.nix
    ./service/safepaste.nix
    ./service/jank-benchmark.nix
    ./service/fail2ban.nix
    ./service/imap-filter.nix
    ./service/radicale.nix
    ./service/gpg.nix
    ./service/jank-license.nix
    ./service/upload.jeaye.com-tmp.nix
    ./service/padwatch.nix
  ];

  system.stateVersion = "16.09";
}
