{ config, pkgs, ... }:

{
  imports =
  [
    ./hardware-configuration.nix # Auto-generated by nixos
    ./nixos-in-place.nix

    ./system/grub.nix
    ./system/environment.nix
    ./system/network.nix
    ./system/user.nix

    ./program/vim.nix
    ./program/irc.nix

    #./service/acme.nix
    ./service/httpd.nix
    ./service/postfix.nix
    ./service/dovecot.nix
    ./service/spam-assassin.nix
    ./service/fiche.nix
    ./service/fail2ban.nix
  ];

  services.locate.enable = true;

  sound.enable = false;

  system.stateVersion = "15.09";
}

# TODO:
# Adopt 16.03 once fail2ban is working
# Users in /etc/user
# Bring in weechat/mutt configs
