{ config, pkgs, ... }:

{
  imports =
  [
    ./hardware-configuration.nix # Auto-generated by nixos

    ./shared/system/grub.nix

    ./shared/system/environment.nix
    ./workstation/system/environment.nix

    ./shared/system/network.nix
    ./workstation/system/network.nix

    ./system/user.nix
    ./system/systemd.nix

    ./program/essentials.nix
    ./program/admin.nix

    ./user/jeaye.nix

    ./service/ssh.nix
    ./service/gpg.nix
  ];

  system.stateVersion = "17.09";
}
