{ config, pkgs, ... }:

{
  imports =
  [
    ./hardware-configuration.nix # Auto-generated by nixos
    ../shared/configuration.nix

    ## More secure defaults
    <nixpkgs/nixos/modules/profiles/hardened.nix>

    ## System
    ./system/boot.nix
    ./system/environment.nix
    ./system/network.nix
    ./system/power.nix
    ./system/security.nix
    ./system/sound.nix

    ## Global programs
    ./program/essential.nix

    ## Users
    ./system/user.nix
    ./user/jeaye.nix

    ## Services
    ./service/manual.nix
    ./service/x11.nix
  ];

  system.stateVersion = "17.09";
}
