{ config, pkgs, ... }:

{
  imports =
  [
    ./hardware-configuration.nix # Auto-generated by nixos

    ../shared/system/grub.nix

    ../shared/system/environment.nix
    ./system/environment.nix

    ../shared/system/network.nix
    ./system/network.nix

    ./system/user.nix
    ../shared/system/systemd.nix

    ./program/essentials.nix

    #./user/jeaye.nix

    ../shared/service/ssh.nix
    ./service/gpg.nix
  ];

  system.stateVersion = "17.09";
}
