# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# News reading
export NNTPSERVER="snews://reader.usenetbucket.com"
if [ ! -f ~/.jnewsrc ];
then
  slrn --create
  slrn -d
fi
