# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# News reading
export NNTPSERVER="snews://reader.usenetbucket.com"
actual_slrn=$(which slrn)
slrn()
{
  if [ ! -f ~/.jnewsrc ];
  then
    $actual_slrn --create $@
    $actual_slrn -d
  else
    $actual_slrn $@
  fi
}
